[package]
name = "lmcc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "lmcc"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lmcc-core = { path = "../lmcc-core" }
lmcc-lang = { path = "../lmcc-lang" }
serde_json.workspace = true
tempfile.workspace = true
ureq.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
