"""CI adapter tests: generated GitLab child pipelines and GitHub matrices."""

import contextlib
import io
import json
from pathlib import Path
import tempfile
import unittest

from .__main__ import main
from .ci import github_matrix, gitlab_child, gitlab_skipped, load_config
from .common import write_json

RECIPE = Path(__file__).resolve().parent / "recipe"
SCORER = "registry.example/llm-cc-scorer@sha256:" + "1" * 64
COORDINATOR = "registry.example/llm-cc-coordinator@sha256:" + "2" * 64
PLAN_PATH = "comparison/prep/plan.json"
STORE = "s3://bucket/llm-cc"


def plan(workers, image=SCORER):
    return {
        "profile": {"build": {"execution_image": image}},
        "workers": [
            {"worker_id": worker_id, "keys": ["k%d" % worker_id], "bytes": 1}
            for worker_id in range(workers)
        ],
    }


def read_yaml(path):
    text = Path(path).read_text(encoding="utf-8")
    # The generated document is JSON after one YAML comment line.
    header, document = text.split("\n", 1)
    assert header.startswith("# Generated by")
    return json.loads(document)


class GitLabChildTest(unittest.TestCase):
    def setUp(self):
        self.config = load_config(RECIPE / "config" / "ci.example.json")

    def jobs(self, document, prefix):
        return {name: job for name, job in document.items() if name.startswith(prefix)}

    def test_one_gpu_job_per_planned_worker(self):
        for count in (0, 1, 4):
            with self.subTest(workers=count):
                child = gitlab_child(
                    plan(count), PLAN_PATH, self.config, STORE, coordinator=COORDINATOR
                )
                workers = self.jobs(child, "comparison-worker-")
                self.assertEqual(len(workers), count)
                for worker_id in range(count):
                    job = workers["comparison-worker-%d" % worker_id]
                    self.assertEqual(job["image"], SCORER)
                    self.assertEqual(job["tags"], ["linux", "gpu", "cuda-sm86"])
                    self.assertIs(job["interruptible"], True)
                    self.assertEqual(job["timeout"], "120m")
                    self.assertEqual(
                        job["needs"],
                        [
                            {
                                "pipeline": "$PARENT_PIPELINE_ID",
                                "job": "comparison-prepare",
                            }
                        ],
                    )
                    self.assertIn("--worker-id %d" % worker_id, job["script"][-1])
                    self.assertEqual(job["artifacts"]["when"], "always")
                    self.assertEqual(
                        job["artifacts"]["paths"],
                        ["comparison/workers/%d/" % worker_id],
                    )
                aggregate = child["comparison-aggregate"]
                self.assertEqual(aggregate["when"], "always")
                self.assertIs(aggregate["interruptible"], True)
                self.assertEqual(
                    [need.get("job") for need in aggregate["needs"][1:]],
                    sorted(workers),
                )
                script = "\n".join(aggregate["script"])
                self.assertIn("llm-cc compare aggregate --plan", script)
                self.assertEqual(script.count("--worker "), count)
                self.assertIn("store-report --cache s3://bucket/llm-cc", script)
                self.assertTrue(aggregate["script"][-1].startswith("exit"))

    def test_fully_cached_plan_needs_no_scorer_image(self):
        child = gitlab_child(
            plan(0, image="none"),
            PLAN_PATH,
            self.config,
            STORE,
            coordinator=COORDINATOR,
        )
        self.assertEqual(sorted(child), ["comparison-aggregate", "stages"])
        self.assertEqual(child["comparison-aggregate"]["image"], COORDINATOR)

    def test_worker_outputs_never_overlap_preparation_artifacts(self):
        child = gitlab_child(
            plan(4), PLAN_PATH, self.config, STORE, coordinator=COORDINATOR
        )
        outputs = [
            path
            for name, job in child.items()
            if name.startswith("comparison-worker-")
            for path in job["artifacts"]["paths"]
        ]
        self.assertEqual(len(set(outputs)), 4)
        self.assertFalse(any(path.startswith("comparison/prep") for path in outputs))

    def test_images_must_be_pinned_by_digest(self):
        for image in (
            "registry.example/scorer:latest",
            "registry.example/scorer@sha256:" + "1" * 63,
            "registry.example/scorer@sha256:" + "A" * 64,
        ):
            with self.subTest(image=image):
                with self.assertRaisesRegex(ValueError, "digest"):
                    gitlab_child(
                        plan(1, image),
                        PLAN_PATH,
                        self.config,
                        STORE,
                        coordinator=COORDINATOR,
                    )
        config = json.loads((RECIPE / "config" / "ci.example.json").read_text())
        config["images"] = {"coordinator": "registry.example/coordinator:1"}
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "ci.json"
            write_json(path, config)
            with self.assertRaisesRegex(ValueError, "coordinator"):
                load_config(path)
        for coordinator in (None, "registry.example/coordinator:1"):
            with self.subTest(coordinator=coordinator):
                with self.assertRaisesRegex(ValueError, "coordinator"):
                    gitlab_child(
                        plan(0), PLAN_PATH, self.config, STORE, {}, coordinator
                    )
        # A configured coordinator applies when the command line names none.
        self.config["images"]["coordinator"] = COORDINATOR
        gitlab_child(plan(0), PLAN_PATH, self.config, STORE)

    def test_configured_scorer_must_match_the_fingerprinted_profile(self):
        self.config["images"]["scorer"] = "registry.example/other@sha256:" + "2" * 64
        with self.assertRaisesRegex(ValueError, "fingerprinted"):
            gitlab_child(
                plan(1), PLAN_PATH, self.config, STORE, coordinator=COORDINATOR
            )
        self.config["images"]["scorer"] = SCORER
        gitlab_child(plan(1), PLAN_PATH, self.config, STORE, coordinator=COORDINATOR)

    def test_capacity_paths_and_store_options_are_validated(self):
        self.config["max_workers"] = 2
        with self.assertRaisesRegex(ValueError, "allows 2"):
            gitlab_child(
                plan(3), PLAN_PATH, self.config, STORE, coordinator=COORDINATOR
            )
        for path in ("/abs/plan.json", "../plan.json"):
            with self.subTest(path=path):
                with self.assertRaisesRegex(ValueError, "relative"):
                    gitlab_child(
                        plan(1), path, self.config, STORE, coordinator=COORDINATOR
                    )
        for key in ("aws_secret_access_key", "AWS_SECRET_ACCESS_KEY", "SessionToken"):
            with self.subTest(key=key):
                with self.assertRaisesRegex(ValueError, "credentials"):
                    gitlab_child(
                        plan(1), PLAN_PATH, self.config, STORE, {key: "x"}, COORDINATOR
                    )
        child = gitlab_child(
            plan(1), PLAN_PATH, self.config, STORE, {"region_name": "it's"}, COORDINATOR
        )
        worker = child["comparison-worker-0"]
        self.assertEqual(
            worker["script"][0],
            """printf '%s' '{"region_name": "it'"'"'s"}' > store-options.json""",
        )
        self.assertIn("--store-options store-options.json", worker["script"][1])

    def test_configuration_is_optional(self):
        config = load_config()
        self.assertEqual(config["scorer"]["model"], "/models/model.gguf")
        self.assertEqual(config["gitlab"]["prepare_job"], "comparison-prepare")
        self.assertNotIn(
            "tags",
            gitlab_child(plan(1), PLAN_PATH, config, STORE, {}, COORDINATOR)[
                "comparison-worker-0"
            ],
        )

    def test_skipped_branch_still_has_one_job(self):
        child = gitlab_skipped(self.config, "no open pull request", COORDINATOR)
        self.assertEqual(child["comparison-skipped"]["image"], COORDINATOR)
        self.assertEqual(list(child), ["comparison-skipped"])
        self.assertEqual(
            child["comparison-skipped"]["script"], ["echo 'no open pull request'"]
        )


class GitHubMatrixTest(unittest.TestCase):
    def test_matrix_outputs(self):
        self.assertEqual(
            github_matrix(plan(0, image="none")),
            {"matrix": '{"include":[]}', "has_workers": "false"},
        )
        self.assertEqual(
            github_matrix(plan(2)),
            {
                "matrix": '{"include":[{"worker_id":0},{"worker_id":1}]}',
                "has_workers": "true",
                "scorer_image": SCORER,
            },
        )
        with self.assertRaisesRegex(ValueError, "digest"):
            github_matrix(plan(1, image="scorer:latest"))


class CommandTest(unittest.TestCase):
    def run_main(self, *arguments):
        output, errors = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(output), contextlib.redirect_stderr(errors):
            status = main(list(arguments))
        return status, output.getvalue(), errors.getvalue()

    def test_commands_write_pipeline_and_outputs(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_json(root / "plan.json", plan(2))
            config = str(RECIPE / "config" / "ci.example.json")
            options = RECIPE / "config" / "store-options.example.json"
            status, output, _ = self.run_main(
                "ci",
                "gitlab-child",
                "--plan",
                str(root / "plan.json"),
                "--config",
                config,
                "--coordinator-image",
                COORDINATOR,
                "--output",
                str(root / "child.yml"),
                "--cache",
                STORE,
                "--store-options",
                str(options),
            )
            # Absolute plan paths do not exist in the downloaded job directory.
            self.assertEqual(status, 1)
            (root / "comparison/prep").mkdir(parents=True)
            write_json(root / PLAN_PATH, plan(2))
            with contextlib.chdir(root):
                status, output, errors = self.run_main(
                    "ci",
                    "gitlab-child",
                    "--plan",
                    PLAN_PATH,
                    "--config",
                    config,
                    "--coordinator-image",
                    COORDINATOR,
                    "--output",
                    "child.yml",
                    "--cache",
                    STORE,
                    "--store-options",
                    str(options),
                )
            self.assertEqual(status, 0, errors)
            self.assertIn("2 GPU worker job(s)", output)
            child = read_yaml(root / "child.yml")
            self.assertIn("comparison-worker-1", child)
            self.assertIn("region_name", child["comparison-worker-1"]["script"][0])
            status, output, errors = self.run_main(
                "ci",
                "gitlab-child",
                "--config",
                config,
                "--coordinator-image",
                COORDINATOR,
                "--output",
                str(root / "skipped.yml"),
                "--skipped",
                "no open pull request",
            )
            self.assertEqual(status, 0, errors)
            self.assertIn("0 GPU worker job(s)", output)
            self.assertEqual(
                list(read_yaml(root / "skipped.yml")), ["comparison-skipped"]
            )
            outputs = root / "github-output"
            outputs.write_text("EXISTING=1\n")
            status, output, _ = self.run_main(
                "ci",
                "github-matrix",
                "--plan",
                str(root / "plan.json"),
                "--github-output",
                str(outputs),
            )
            self.assertEqual(status, 0)
            lines = outputs.read_text().splitlines()
            self.assertEqual(lines[0], "EXISTING=1")
            self.assertIn("has_workers=true", lines)
            self.assertIn("scorer_image=" + SCORER, lines)


if __name__ == "__main__":
    unittest.main()
